# Generated by Django 5.2.5 on 2025-09-14 09:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='short_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
